### PR TITLE
Spec typos

### PR DESCRIPTION
**Pull request by danielkec**
Signed-off-by: Daniel Kec <daniel.kec@oracle.com>

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by danielkec** [comment]
Fixes #102

**Comment by Azquelt** [comment]
@genie-microprofile build this please

**Comment by Azquelt** [comment]
@genie-microprofile test this please :roll_eyes:

**Comment by cescoffier** [comment]
Thanks!

**Pull request merged**
