### PR TITLE
Spec and TCK for message count metrics

### PR DESCRIPTION
**Pull request by Azquelt**
Part of #31 

Add spec and tests a metric for the number of messages sent through a channel.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Is there an implementation that verifies the intended behavior?

**Comment by Azquelt** [comment]
I'm just cleaning up the PR for smallrye reactive messaging

**Comment by Azquelt** [comment]
The implementation for this has now been merged in smallrye-reactive-messaging

**Comment by cescoffier** [comment]
Looks good to me.

**Pull request merged**
