### PR TITLE
Fix incorrect bean name, issue #76

### PR DESCRIPTION
**Pull request by lamtrhieu**
Fix https://github.com/eclipse/microprofile-reactive-messaging/issues/76

### CODE REVIEW

**Comment by lamtrhieu** [comment]
@cescoffier Can you please have a quick look if the fix is ok. One problem is that I cannot run the test on my local computer. 
My intellij complain "Arquillian test class should have only 1 method with Deployment annotation" and when I run the test I cannot see any result. 
Can you please advise how can I fix that and run the tests?
Thanks

**Comment by cescoffier** [comment]
The fix looks good to me.

You need to sign the Eclipse CLA and sign-off your commit.

**Comment by lamtrhieu** [comment]
Yes, I know that. But can you show me how I can run the tests on my local computer ?
There seems like error in my IntelliJ with the error "Arquillian test class should have only 1 method with Deployment annotation"

**Comment by cescoffier** [comment]
@lamtrhieu you need to test again an implementation. Build the package and update the smallrye implementation to use your tck artifact.

**Comment by lamtrhieu** [comment]
@cescoffier I have successfully built the package now. How can I test smallrye implementation using the new tck package? I have checked out project **smallrye-reactive-messaging** already. 
I guess I need to edit the pom file and run some mvn command ? 
Can you please help me with the steps ? Thank you so much for that.

**Comment by cescoffier** [comment]
You just need to change the MicroProfile Reactive Messaging version in the `pom.xml` file and run `mvn clean install`. 

The fast track would be to just build the `tck` module, that should be enough.

**Comment by lamtrhieu** [comment]
Hi @cescoffier  
I build the tck project using my updated tck artifact and it get error with that test

"java.lang.RuntimeException: Expected exception of type javax.enterprise.inject.spi.DeploymentException during deployment of incomplete-chain, but no exception was thrown."

It's clear that no exception is thrown when deploy the bean. Can you please help me to understand why the bean is named "BeanWithIncompleteChain" and why it should throw exception with that kind of bean ?

**Comment by cescoffier** [comment]
so... you just found a feature :-)

I was able to get the TCK passing by enabling the strict mode of smallrye reactive messaging (System.setProperty(STRICT_MODE_PROPERTY, "true");).

It means that we are all good with your PR.

**Comment by cescoffier** [comment]
Thanks!

**Comment by lamtrhieu** [comment]
@cescoffier If there any problem that need a little more "lines" to fix then just tag me in. I am happy to have a look.

**Pull request merged**
